--- # EC2 KEY MODULE
- hosts: localhost
  connection: local
  remote_user: admin
  become: yes
  gather_facts: no
  vars_files:
  - files/aws_creds.yml
  tasks:
  - name: Create - Delete Key Pair
    ec2_key: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      name: KeyPairTest
      region: us-east-2
      state: absent
